branch-defaults:
  AWSUpload:
    environment: LowCost-env
environment-defaults:
  LowCost-env:
    branch: null
    repository: null
global:
  application_name: cuoiky-cc
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-1::platform/Tomcat 8 with
    Java 8 running on 64bit Amazon Linux/2.6.0
  default_region: ap-southeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
